const exData=[
    {id:1,exercise:'Abdominal Crunches',calories:6,type:2},
    {id:2,exercise:'Abdominal Leg Raise',calories:6,type:2},
    {id:3,exercise:'Abdominal Twist, Seated, Machine',calories:6,type:2},
    {id:4,exercise:'Back Butterfly',calories:6,type:2},
    {id:5,exercise:'Back Extension',calories:6,type:2},
    {id:6,exercise:'Bar Dip, Palms In, Neutral Grip',calories:6,type:2},
    {id:7,exercise:'Barbell Military Press',calories:6,type:2},
    {id:8,exercise:'Barbell Row, Bent-over',calories:5,type:2},
    {id:9,exercise:'Bench (Chest) Press, Machine',calories:5,type:2},
    {id:10,exercise:'Bench Press, Barbell',calories:5,type:2},
    {id:11,exercise:'Bent Arm Barbell Pullover',calories:5,type:2},
    {id:12,exercise:'Bent Arm Barbell Pullover and Press',calories:5,type:2},
    {id:13,exercise:'Bent-Arm Lateral',calories:5,type:2},
    {id:14,exercise:'Bent-Leg Kickbacks',calories:5,type:2},
    {id:15,exercise:'Bent-Over Low-Pulley Side Lateral',calories:5,type:2},
    {id:16,exercise:'Cable Crossover, High Pulley',calories:4,type:2},
    {id:17,exercise:'Calf Raises, Single-Leg',calories:4,type:2},
    {id:18,exercise:'Deadlift, Straight Leg',calories:4,type:2},
    {id:19,exercise:'Dumbbell Press, One-Arm, Palm-In',calories:4,type:2},
    {id:20,exercise:'Dumbbell Press, Seated, Palms-In',calories:4,type:2},
    {id:21,exercise:'Dumbbell Row, One-Arm, Bent-Over',calories:4,type:2},
    {id:22,exercise:'Dumbbell Row, Two-Arm, Bent-Over',calories:4,type:2},
    {id:23,exercise:'Flat Dumbbell Fly',calories:4,type:2},
    {id:24,exercise:'Flat Dumbbell Press',calories:4,type:2},
    {id:25,exercise:'Front Barbell Raise, Standing, Medium-Grip',calories:4,type:2},
    {id:26,exercise:'Front Chin Up, Close-Grip, Palms Back',calories:4,type:2},
    {id:27,exercise:'Front Raises, Straight Arm',calories:4,type:2},
    {id:28,exercise:'Front Squats, Barbell, Arms Crossed',calories:4,type:2},
    {id:29,exercise:'Hack Squat',calories:4,type:2},
    {id:30,exercise:'Heel Raise',calories:4,type:2},
    {id:31,exercise:'Hip Abduction, Machine, Seated',calories:4,type:2},
    {id:32,exercise:'Hip Flexor, Machine, Standing',calories:4,type:2},
    {id:33,exercise:'Incline Lateral, Dumbbells',calories:4,type:2},
    {id:34,exercise:'Kickbacks, Bent, 1-Arm, Dumbbell',calories:4,type:2},
    {id:35,exercise:'Kickbacks, Bent, 2-Arm, Dumbbell',calories:4,type:2},
    {id:36,exercise:'Lat Pulldown',calories:4,type:2},
    {id:37,exercise:'Lateral Arm Raise, Machine',calories:4,type:2},
    {id:38,exercise:'Lateral Raise, Dumbbell, Side',calories:4,type:2},
    {id:39,exercise:'Leg Pull-In, Seated Flat Bench',calories:4,type:2},
    {id:40,exercise:'Leg Raises, Hanging',calories:4,type:2},
    {id:41,exercise:'Machine Fly',calories:4,type:2},
    {id:42,exercise:'Machine Squat',calories:4,type:2},
    {id:43,exercise:'Mid Row, Chest Supported, Machine',calories:4,type:2},
    {id:44,exercise:'Overhead Press, Barbell',calories:4,type:2},
    {id:45,exercise:'Overhead Press, Machine, Seated',calories:4,type:2},
    {id:46,exercise:'Pec Dec Butterfly (Pectoral Fly)',calories:4,type:2},
    {id:47,exercise:'Preacher Bench Medium-Grip Barbell Curl',calories:4,type:2},
    {id:48,exercise:'Rear Deltoid Raise',calories:4,type:2},
    {id:49,exercise:'Seated Biceps Curl',calories:4,type:2},
    {id:50,exercise:'Seated Calf Raise',calories:4,type:2},
    {id:51,exercise:'Seated Row, Floor, Machine',calories:4,type:2},
    {id:52,exercise:'Seated, Low Lat Pull-In, Two-Arm',calories:4,type:2},
    {id:53,exercise:'Side Bends, Barbell',calories:4,type:2},
    {id:54,exercise:'Side Leg Raises',calories:4,type:2},
    {id:55,exercise:'Squat',calories:4,type:2},
    {id:56,exercise:'Standing Bar Curl, Machine',calories:4,type:2},
    {id:57,exercise:'Standing Biceps Curl, Dumbell',calories:4,type:2},
    {id:58,exercise:'Standing Calf Raises',calories:4,type:2},
    {id:59,exercise:'Standing Medium-Grip Barbell Curl',calories:4,type:2},
    {id:60,exercise:'Standing One-Arm Curl, Low Pulley',calories:4,type:2},
    {id:61,exercise:'Standing One-Arm Dumbbell Curl',calories:4,type:2},
    {id:62,exercise:'Straight Arm Dumbbell Pullover',calories:4,type:2},
    {id:63,exercise:'V-Bar Chin Up, Neutral Grip, Palms In',calories:4,type:2},
    {id:64,exercise:'Vertical Leg Lift, Knees Bent (Dip Bars)',calories:4,type:2},
    {id:65,exercise:'Vertical Leg Lift, Knees Straight (Dip Bars)',calories:4,type:2},
    {id:66,exercise:'9Round',calories:4,type:1},
    {id:67,exercise:'Abs',calories:4,type:1},
    {id:68,exercise:'Activity tracker',calories:4,type:1},
    {id:69,exercise:'Adaptive Motion Trainer',calories:4,type:1},
    {id:70,exercise:'Aerobics',calories:4,type:1},
    {id:71,exercise:'Aerobics, general',calories:4,type:1},
    {id:72,exercise:'Aerobics, high impact',calories:4,type:1},
    {id:73,exercise:'Aerobics, low impact',calories:5,type:1},
    {id:74,exercise:'Aerobics, step, with 10-12 inch step',calories:5,type:1},
    {id:75,exercise:'Aerobics, step, with 6-8 inch step',calories:5,type:1},
    {id:76,exercise:'Aquathlon',calories:5,type:1},
    {id:77,exercise:'Archery (non-hunting)',calories:5,type:1},
    {id:78,exercise:'Automobile repair',calories:5,type:1},
    {id:79,exercise:'Backpacking, general',calories:5,type:1},
    {id:80,exercise:'Badminton, competitive',calories:5,type:1},
    {id:81,exercise:'Badminton, social, general',calories:5,type:1},
    {id:82,exercise:'Barre',calories:5,type:1},
    {id:83,exercise:'Barre3',calories:5,type:1},
    {id:84,exercise:'Barrys Bootcamp',calories:5,type:1},
    {id:85,exercise:'Baseball',calories:5,type:1},
    {id:86,exercise:'Basketball',calories:5,type:1},
    {id:87,exercise:'Basketball, game',calories:5,type:1},
    {id:88,exercise:'Basketball, nongame, general',calories:5,type:1},
    {id:89,exercise:'Basketball, officiating',calories:5,type:1},
    {id:90,exercise:'Basketball, shooting baskets',calories:5,type:1},
    {id:91,exercise:'Basketball, wheelchair',calories:5,type:1},
    {id:92,exercise:'Beat Saber',calories:5,type:1},
    {id:93,exercise:'Belly dancing',calories:5,type:1},
    {id:94,exercise:'Bent-Knee Sit-Up',calories:5,type:1},
    {id:95,exercise:'Biceps Curl',calories:5,type:1},
    {id:96,exercise:'Bicycling',calories:5,type:1},
    {id:97,exercise:'Bicycling, &lt;10 mph, leisure (cycling, biking, bike riding)',calories:5,type:1},
    {id:98,exercise:'Bicycling, 10-12 mph, light (cycling, biking, bike riding)',calories:5,type:1},
    {id:99,exercise:'Bicycling, 12-14 mph, moderate (cycling, biking, bike riding)',calories:5,type:1},
    {id:100,exercise:'Bicycling, 14-16 mph, vigorous (cycling, biking, bike riding)',calories:5,type:1},
    {id:101,exercise:'Bicycling, 16-20 mph, very fast (cycling, biking, bike riding)',calories:5,type:1},
    {id:102,exercise:'Bicycling, &gt;20 mph, racing (cycling, biking, bike riding)',calories:5,type:1},
    {id:103,exercise:'Bicycling, BMX or mountain (cycling, biking, bike riding)',calories:5,type:1},
    {id:104,exercise:'Bicycling, commuting, mountain biking',calories:5,type:1},
    {id:105,exercise:'Bicycling, commuting, road cycling',calories:5,type:1},
    {id:106,exercise:'Bicycling, cruiser bike',calories:5,type:1},
    {id:107,exercise:'Bicycling, fixed gear',calories:5,type:1},
    {id:108,exercise:'Bicycling, hybrid cycling',calories:5,type:1},
    {id:109,exercise:'Bicycling, indoor',calories:5,type:1},
    {id:110,exercise:'Bicycling, mountain',calories:5,type:1},
    {id:111,exercise:'Bicycling, road cycle',calories:5,type:1},
    {id:112,exercise:'Bicycling, stationary',calories:5,type:1},
    {id:113,exercise:'Bicycling, touring bike',calories:5,type:1},
    {id:114,exercise:'Bikram Yoga',calories:5,type:1},
    {id:115,exercise:'Billiards',calories:5,type:1},
    {id:116,exercise:'Body Pump',calories:5,type:1},
    {id:117,exercise:'Body weight squats',calories:5,type:1},
    {id:118,exercise:'Bootcamp workout',calories:5,type:1},
    {id:119,exercise:'Bowling',calories:5,type:1},
    {id:120,exercise:'Boxing, in ring, general',calories:5,type:1},
    {id:121,exercise:'Boxing, punching bag',calories:5,type:1},
    {id:122,exercise:'Boxing, sparring',calories:5,type:1},
    {id:123,exercise:'Brazilian Jiu Jitsu',calories:5,type:1},
    {id:124,exercise:'Broomball',calories:5,type:1},
    {id:125,exercise:'Calisthenics',calories:5,type:1},
    {id:126,exercise:'Calisthenics (pushups, sit-ups), vigorous effort',calories:5,type:1},
    {id:127,exercise:'Calisthenics, home, light/moderate effort',calories:5,type:1},
    {id:128,exercise:'Camp Gladiator',calories:5,type:1},
    {id:129,exercise:'Canoeing, on camping trip',calories:5,type:1},
    {id:130,exercise:'Canoeing, rowing, &gt;6 mph, vigorous effort',calories:5,type:1},
    {id:131,exercise:'Canoeing, rowing, crewing, competition',calories:5,type:1},
    {id:132,exercise:'Canoeing, rowing, light effort',calories:5,type:1},
    {id:133,exercise:'Canoeing, rowing, moderate effort',calories:5,type:1},
    {id:134,exercise:'Carpentry, general',calories:5,type:1},
    {id:135,exercise:'Chair Yoga',calories:5,type:1},
    {id:136,exercise:'Cheerleading',calories:5,type:1},
    {id:137,exercise:'Chin-Ups',calories:5,type:1},
    {id:138,exercise:'Chopping wood',calories:5,type:1},
    {id:139,exercise:'Circuit training',calories:5,type:1},
    {id:140,exercise:'Circuit training, Cardiovascular (CV)',calories:5,type:1},
    {id:141,exercise:'Circuit training, Resistance',calories:5,type:1},
    {id:142,exercise:'Circuit training, general',calories:5,type:1},
    {id:143,exercise:'Class',calories:5,type:1},
    {id:144,exercise:'Cleaning, heavy, vigorous effort',calories:5,type:1},
    {id:145,exercise:'Cleaning, light',calories:5,type:1},
    {id:146,exercise:'Cleaning, light, moderate effort',calories:5,type:1},
    {id:147,exercise:'Club Pilates',calories:5,type:1},
    {id:148,exercise:'Coaching: football, soccer, basketball, etc.',calories:5,type:1},
    {id:149,exercise:'Combat class',calories:5,type:1},
    {id:150,exercise:'Concept2 BikErg',calories:5,type:1},
    {id:151,exercise:'Concept2 SkiErg',calories:5,type:1},
    {id:152,exercise:'Cooking or food preparation',calories:5,type:1},
    {id:153,exercise:'CorePower Yoga',calories:5,type:1},
    {id:154,exercise:'Crew',calories:5,type:1},
    {id:155,exercise:'Crewing',calories:5,type:1},
    {id:156,exercise:'Cricket (batting, bowling)',calories:5,type:1},
    {id:157,exercise:'Croquet',calories:5,type:1},
    {id:158,exercise:'Cross Trainer',calories:5,type:1},
    {id:159,exercise:'CrossFit',calories:5,type:1},
    {id:160,exercise:'Crunches and leg lifts',calories:5,type:1},
    {id:161,exercise:'Curling',calories:5,type:1},
    {id:162,exercise:'Curves Circuit Training',calories:5,type:1},
    {id:163,exercise:'CycleBar',calories:5,type:1},
    {id:164,exercise:'Dancing',calories:5,type:1},
    {id:165,exercise:'Dancing, aerobic, ballet or modern, twist',calories:5,type:1},
    {id:166,exercise:'Dancing, ballroom, fast',calories:5,type:1},
    {id:167,exercise:'Dancing, ballroom, slow',calories:5,type:1},
    {id:168,exercise:'Dancing, general',calories:5,type:1},
    {id:169,exercise:'Darts, wall or lawn',calories:5,type:1},
    {id:170,exercise:'Decline Bench Press',calories:5,type:1},
    {id:171,exercise:'Decline Dumbbell Fly',calories:5,type:1},
    {id:172,exercise:'Dips',calories:5,type:1},
    {id:173,exercise:'Disc Golf',calories:5,type:1},
    {id:174,exercise:'Diving, springboard or platform',calories:5,type:1},
    {id:175,exercise:'Double Stroller, Bike',calories:5,type:1},
    {id:176,exercise:'Elliptical Trainer',calories:5,type:1},
    {id:177,exercise:'Elliptical, Under Desk',calories:5,type:1},
    {id:178,exercise:'EverybodyFights',calories:5,type:1},
    {id:179,exercise:'F45 Training',calories:5,type:1},
    {id:180,exercise:'Fencing',calories:5,type:1},
    {id:181,exercise:'Fhitting Room',calories:5,type:1},
    {id:182,exercise:'Fishing',calories:5,type:1},
    {id:183,exercise:'Fishing from boat, sitting',calories:5,type:1},
    {id:184,exercise:'Fishing from river bank, standing',calories:5,type:1},
    {id:185,exercise:'Fishing in stream, in waders',calories:5,type:1},
    {id:186,exercise:'Fishing, general',calories:5,type:1},
    {id:187,exercise:'Fishing, ice, sitting',calories:5,type:1},
    {id:188,exercise:'Fitness band',calories:5,type:1},
    {id:189,exercise:'Fixie Race/Event',calories:5,type:1},
    {id:190,exercise:'Flywheel',calories:5,type:1},
    {id:191,exercise:'Football',calories:5,type:1},
    {id:192,exercise:'Football or baseball, playing catch',calories:5,type:1},
    {id:193,exercise:'Football, competitive',calories:5,type:1},
    {id:194,exercise:'Football, touch, flag, general',calories:5,type:1},
    {id:195,exercise:'FreeLetics',calories:5,type:1},
    {id:196,exercise:'Frisbee playing, general',calories:5,type:1},
    {id:197,exercise:'Frisbee, ultimate',calories:5,type:1},
    {id:198,exercise:'Front Chin Up, Reverse Close-Grip',calories:5,type:1},
    {id:199,exercise:'Gardening',calories:5,type:1},
    {id:200,exercise:'Gardening, general',calories:5,type:1},
    {id:201,exercise:'Generic',calories:5,type:1},
    {id:202,exercise:'Golf, carrying clubs',calories:5,type:1},
    {id:203,exercise:'Golf, miniature or driving range',calories:5,type:1},
    {id:204,exercise:'Golf, pulling clubs',calories:5,type:1},
    {id:205,exercise:'Golf, using power cart',calories:5,type:1},
    {id:206,exercise:'Golfing',calories:5,type:1},
    {id:207,exercise:'Gym',calories:5,type:1},
    {id:208,exercise:'Gym Workout',calories:5,type:1},
    {id:209,exercise:'Gym, Jacobs ladder',calories:5,type:1},
    {id:210,exercise:'Gym, TRX',calories:5,type:1},
    {id:211,exercise:'Gym, abs/core',calories:5,type:1},
    {id:212,exercise:'Gym, back',calories:5,type:1},
    {id:213,exercise:'Gym, chest',calories:5,type:1},
    {id:214,exercise:'Gym, exercise bike',calories:5,type:1},
    {id:215,exercise:'Gym, kettlebell',calories:5,type:1},
    {id:216,exercise:'Gym, legs',calories:5,type:1},
    {id:217,exercise:'Gym, misc',calories:5,type:1},
    {id:218,exercise:'Gym, other machine',calories:5,type:1},
    {id:219,exercise:'Gym, rowing machine',calories:5,type:1},
    {id:220,exercise:'Gym, stair machine',calories:5,type:1},
    {id:221,exercise:'Gym, total body',calories:5,type:1},
    {id:222,exercise:'Gym, treadmill',calories:5,type:1},
    {id:223,exercise:'Gym, upper body',calories:5,type:1},
    {id:224,exercise:'Gym, versa climber',calories:3,type:1},
    {id:225,exercise:'Gymnastics',calories:3,type:1},
    {id:226,exercise:'Gymnastics, general',calories:3,type:1},
    {id:227,exercise:'HIIT',calories:3,type:1},
    {id:228,exercise:'Hacky sack',calories:3,type:1},
    {id:229,exercise:'Handball, general',calories:3,type:1},
    {id:230,exercise:'Handball, team',calories:3,type:1},
    {id:231,exercise:'Hiking',calories:3,type:1},
    {id:232,exercise:'Hiking, climbing hills (carrying &lt;10 lb load)',calories:3,type:1},
    {id:233,exercise:'Hiking, climbing hills (carrying 10-20 lb load)',calories:3,type:1},
    {id:234,exercise:'Hiking, cross country',calories:3,type:1},
    {id:235,exercise:'Hockey',calories:3,type:1},
    {id:236,exercise:'Hockey, field',calories:3,type:1},
    {id:237,exercise:'Hockey, ice',calories:3,type:1},
    {id:238,exercise:'Home Workout',calories:3,type:1},
    {id:239,exercise:'Horse grooming',calories:3,type:1},
    {id:240,exercise:'Horseback riding',calories:3,type:1},
    {id:241,exercise:'Horseback riding, general',calories:3,type:1},
    {id:242,exercise:'Horseback riding, trotting',calories:3,type:1},
    {id:243,exercise:'Horseback riding, walking',calories:3,type:1},
    {id:244,exercise:'Hunting',calories:3,type:1},
    {id:245,exercise:'Hunting, general',calories:3,type:1},
    {id:246,exercise:'Hyperextensions',calories:3,type:1},
    {id:247,exercise:'Incline Bench Press',calories:3,type:1},
    {id:248,exercise:'Incline Dumbbell Curl',calories:3,type:1},
    {id:249,exercise:'Incline Dumbbell Fly',calories:3,type:1},
    {id:250,exercise:'Indoor bike trainer',calories:3,type:1},
    {id:251,exercise:'Insanity',calories:3,type:1},
    {id:252,exercise:'Jai alai',calories:3,type:1},
    {id:253,exercise:'Jet skiing (riding jet ski, water ski-mobiling)',calories:3,type:1},
    {id:254,exercise:'Judo, karate, kick boxing, tae kwan do',calories:3,type:1},
    {id:255,exercise:'Jump roping',calories:3,type:1},
    {id:256,exercise:'Jumping jacks, vigorous',calories:3,type:1},
    {id:257,exercise:'Kangoo Jumps',calories:3,type:1},
    {id:258,exercise:'Kayaking',calories:3,type:1},
    {id:259,exercise:'Kickball',calories:3,type:1},
    {id:260,exercise:'Kickboxing',calories:3,type:1},
    {id:261,exercise:'Kickboxing (including Turbo Jam)',calories:3,type:1},
    {id:262,exercise:'LES MILLS GRIT™',calories:3,type:1},
    {id:263,exercise:'Lacrosse',calories:3,type:1},
    {id:264,exercise:'Lagree Fitness™',calories:3,type:1},
    {id:265,exercise:'Laps',calories:3,type:1},
    {id:266,exercise:'Lawn mowing',calories:3,type:1},
    {id:267,exercise:'Leg Curls',calories:3,type:1},
    {id:268,exercise:'Leg Extension',calories:3,type:1},
    {id:269,exercise:'Leg Press',calories:3,type:1},
    {id:270,exercise:'Les Mills BODYATTACK™',calories:3,type:1},
    {id:271,exercise:'Les Mills BODYBALANCE™/BODYFLOW®',calories:3,type:1},
    {id:272,exercise:'Les Mills BODYCOMBAT™',calories:3,type:1},
    {id:273,exercise:'Les Mills BODYPUMP™',calories:3,type:1},
    {id:274,exercise:'Les Mills BODYSTEP™',calories:3,type:1},
    {id:275,exercise:'Les Mills RPM™',calories:3,type:1},
    {id:276,exercise:'Line dancing',calories:3,type:1},
    {id:277,exercise:'Lower body',calories:3,type:1},
    {id:278,exercise:'Lunge',calories:3,type:1},
    {id:279,exercise:'Marching band, playing instrument(walking)',calories:3,type:1},
    {id:280,exercise:'Marching, rapidly, military',calories:3,type:1},
    {id:281,exercise:'Martial arts',calories:3,type:1},
    {id:282,exercise:'Mild stretching',calories:3,type:1},
    {id:283,exercise:'Mirror',calories:3,type:1},
    {id:284,exercise:'Misc tasks, moderate',calories:3,type:1},
    {id:285,exercise:'Motocross',calories:3,type:1},
    {id:286,exercise:'Moving furniture, household',calories:3,type:1},
    {id:287,exercise:'Moving household items, boxes, upstairs',calories:3,type:1},
    {id:288,exercise:'Moving household items, carrying boxes',calories:3,type:1},
    {id:289,exercise:'Mowing lawn, general',calories:3,type:1},
    {id:290,exercise:'Mowing lawn, riding mower',calories:3,type:1},
    {id:291,exercise:'Music playing, cello, flute, horn, woodwind',calories:3,type:1},
    {id:292,exercise:'Music playing, drums',calories:3,type:1},
    {id:293,exercise:'Music playing, guitar, classical, folk(sitting)',calories:3,type:1},
    {id:294,exercise:'Music playing, guitar, rock/roll band(standing)',calories:3,type:1},
    {id:295,exercise:'Music playing, piano, organ, violin, trumpet',calories:3,type:1},
    {id:296,exercise:'Netball',calories:3,type:1},
    {id:297,exercise:'November Project',calories:3,type:1},
    {id:298,exercise:'Orangetheory',calories:3,type:1},
    {id:299,exercise:'P90X',calories:3,type:1},
    {id:300,exercise:'POP Tennis',calories:3,type:1},
    {id:301,exercise:'PT session',calories:3,type:1},
    {id:302,exercise:'Paddle Tennis',calories:3,type:1},
    {id:303,exercise:'Paddleboat',calories:3,type:1},
    {id:304,exercise:'Pedal Kayak',calories:3,type:1},
    {id:305,exercise:'Peloton',calories:3,type:1},
    {id:306,exercise:'Peloton Bike',calories:3,type:1},
    {id:307,exercise:'Peloton Digital',calories:3,type:1},
    {id:308,exercise:'Peloton Studio',calories:3,type:1},
    {id:309,exercise:'Peloton Tread',calories:3,type:1},
    {id:310,exercise:'Pelvic Lifts',calories:3,type:1},
    {id:311,exercise:'Pickleball',calories:3,type:1},
    {id:312,exercise:'Pilates',calories:3,type:1},
    {id:313,exercise:'Pilates ProWorks',calories:3,type:1},
    {id:314,exercise:'Pilates Reformer',calories:3,type:1},
    {id:315,exercise:'Pilates video',calories:3,type:1},
    {id:316,exercise:'Plank hold',calories:3,type:1},
    {id:317,exercise:'Pole Dancing',calories:3,type:1},
    {id:318,exercise:'Polo',calories:3,type:1},
    {id:319,exercise:'Pull Ups (pull-ups)',calories:3,type:1},
    {id:320,exercise:'Pull-ups, vigorous',calories:3,type:1},
    {id:321,exercise:'Pullover',calories:3,type:1},
    {id:322,exercise:'Pump',calories:3,type:1},
    {id:323,exercise:'Punching bag',calories:3,type:1},
    {id:324,exercise:'Pure Barre',calories:3,type:1},
    {id:325,exercise:'Push Ups (push-ups)',calories:3,type:1},
    {id:326,exercise:'Push-ups',calories:3,type:1},
    {id:327,exercise:'Push-ups, vigorous',calories:3,type:1},
    {id:328,exercise:'Pushing or pulling stroller with child',calories:3,type:1},
    {id:329,exercise:'Race walking',calories:3,type:1},
    {id:330,exercise:'Racquetball, casual, general',calories:3,type:1},
    {id:331,exercise:'Racquetball, competitive',calories:3,type:1},
    {id:332,exercise:'Raking lawn',calories:3,type:1},
    {id:333,exercise:'Rappelling',calories:3,type:1},
    {id:334,exercise:'Recumbant Trike',calories:3,type:1},
    {id:335,exercise:'Reverse Sit-Up',calories:3,type:1},
    {id:336,exercise:'Reverse Trunk Twist',calories:3,type:1},
    {id:337,exercise:'Rock climbing',calories:3,type:1},
    {id:338,exercise:'Rock climbing, ascending rock',calories:3,type:1},
    {id:339,exercise:'Rock climbing, rappelling',calories:3,type:1},
    {id:340,exercise:'Roller blading (in-line skating)',calories:3,type:1},
    {id:341,exercise:'Rollerblading',calories:3,type:1},
    {id:342,exercise:'Rope jumping, fast',calories:3,type:1},
    {id:343,exercise:'Rope jumping, moderate, general',calories:3,type:1},
    {id:344,exercise:'Rope jumping, slow',calories:3,type:1},
    {id:345,exercise:'Rowing',calories:3,type:1},
    {id:346,exercise:'Rowing, stationary, light effort',calories:3,type:1},
    {id:347,exercise:'Rowing, stationary, moderate effort',calories:3,type:1},
    {id:348,exercise:'Rowing, stationary, very vigorous effort',calories:3,type:1},
    {id:349,exercise:'Rowing, stationary, vigorous effort',calories:3,type:1},
    {id:350,exercise:'Rucking, Heavy Pack',calories:3,type:1},
    {id:351,exercise:'Rucking, Light Pack',calories:3,type:1},
    {id:352,exercise:'Rucking, Medium Pack',calories:3,type:1},
    {id:353,exercise:'Rugby',calories:3,type:1},
    {id:354,exercise:'Rumble Boxing',calories:3,type:1},
    {id:355,exercise:'Running',calories:3,type:1},
    {id:356,exercise:'Running (jogging), 10 mph (6 min mile)',calories:3,type:1},
    {id:357,exercise:'Running (jogging), 10.9 mph (5.5 min mile)',calories:3,type:1},
    {id:358,exercise:'Running (jogging), 5 mph (12 min mile)',calories:3,type:1},
    {id:359,exercise:'Running (jogging), 5.2 mph (11.5 min mile)',calories:3,type:1},
    {id:360,exercise:'Running (jogging), 6 mph (10 min mile)',calories:3,type:1},
    {id:361,exercise:'Running (jogging), 6.7 mph (9 min mile)',calories:3,type:1},
    {id:362,exercise:'Running (jogging), 7 mph (8.5 min mile)',calories:3,type:1},
    {id:363,exercise:'Running (jogging), 7.5 mph (8 min mile)',calories:3,type:1},
    {id:364,exercise:'Running (jogging), 8 mph (7.5 min mile)',calories:3,type:1},
    {id:365,exercise:'Running (jogging), 8.6 mph (7 min mile)',calories:3,type:1},
    {id:366,exercise:'Running (jogging), 9 mph (6.5 min mile)',calories:3,type:1},
    {id:367,exercise:'Running (jogging), in place',calories:3,type:1},
    {id:368,exercise:'Running (jogging), indoor',calories:3,type:1},
    {id:369,exercise:'Running (jogging), training, pushing wheelchair',calories:3,type:1},
    {id:370,exercise:'Running (jogging), up stairs',calories:3,type:1},
    {id:371,exercise:'Running, adventure race',calories:3,type:1},
    {id:372,exercise:'Running, brick',calories:3,type:1},
    {id:373,exercise:'Running, cross country',calories:3,type:1},
    {id:374,exercise:'Running, elliptical',calories:3,type:1},
    {id:375,exercise:'Running, general',calories:3,type:1},
    {id:376,exercise:'Running, group',calories:3,type:1},
    {id:377,exercise:'Running, hills',calories:3,type:1},
    {id:378,exercise:'Running, interval training',calories:3,type:1},
    {id:379,exercise:'Running, race/event',calories:3,type:1},
    {id:380,exercise:'Running, sprints',calories:3,type:1},
    {id:381,exercise:'Running, trail',calories:3,type:1},
    {id:382,exercise:'Running, treadmill',calories:3,type:1},
    {id:383,exercise:'Running, with dog',calories:3,type:1},
    {id:384,exercise:'Running, with stroller',calories:3,type:1},
    {id:385,exercise:'SLT',calories:3,type:1},
    {id:386,exercise:'Sailing, boat/board, windsurfing, general',calories:3,type:1},
    {id:387,exercise:'Sailing, in competition',calories:3,type:1},
    {id:388,exercise:'Shoulder Press',calories:3,type:1},
    {id:389,exercise:'Shoulder Shrug',calories:3,type:1},
    {id:390,exercise:'Shoveling snow',calories:3,type:1},
    {id:391,exercise:'Shred415',calories:3,type:1},
    {id:392,exercise:'Shuffleboard, lawn bowling',calories:3,type:1},
    {id:393,exercise:'Single Stroller, Bike',calories:3,type:1},
    {id:394,exercise:'Sit-Ups',calories:3,type:1},
    {id:395,exercise:'Sit-ups, vigorous',calories:3,type:1},
    {id:396,exercise:'Skateboarding',calories:3,type:1},
    {id:397,exercise:'Skating, ice, 9 mph or less',calories:3,type:1},
    {id:398,exercise:'Skating, ice, general',calories:3,type:1},
    {id:399,exercise:'Skating, ice, rapidly, &gt; 9 mph',calories:3,type:1},
    {id:400,exercise:'Skating, ice, speed, competitive',calories:3,type:1},
    {id:401,exercise:'Skating, roller (rollerblading, roller blading)',calories:3,type:1},
    {id:402,exercise:'Ski jumping (climb up carrying skis)',calories:3,type:1},
    {id:403,exercise:'Ski machine, general',calories:3,type:1},
    {id:404,exercise:'Skiing, cross-country, 2.5 mph, slow or light effort',calories:3,type:1},
    {id:405,exercise:'Skiing, cross-country, 4-5 mph, moderate effort',calories:3,type:1},
    {id:406,exercise:'Skiing, cross-country, 5-8 mph, vigorous effort',calories:3,type:1},
    {id:407,exercise:'Skiing, cross-country, &gt;8.0 mph, racing',calories:3,type:1},
    {id:408,exercise:'Skiing, cross-country, uphill, maximum effort',calories:3,type:1},
    {id:409,exercise:'Skiing, downhill, light effort',calories:3,type:1},
    {id:410,exercise:'Skiing, downhill, moderate effort',calories:3,type:1},
    {id:411,exercise:'Skiing, downhill, vigorous effort, racing',calories:3,type:1},
    {id:412,exercise:'Skiing, snow, general',calories:3,type:1},
    {id:413,exercise:'Skiing, water',calories:3,type:1},
    {id:414,exercise:'Skin diving, scuba diving, general',calories:3,type:1},
    {id:415,exercise:'Sledding, tobogganing, bobsledding, luge',calories:3,type:1},
    {id:416,exercise:'Slimnastics, jazzercise',calories:3,type:1},
    {id:417,exercise:'Snorkeling',calories:3,type:1},
    {id:418,exercise:'Snow shoeing',calories:3,type:1},
    {id:419,exercise:'Snow skiing',calories:7,type:1},
    {id:420,exercise:'Snowboarding',calories:7,type:1},
    {id:421,exercise:'Snowmobiling',calories:7,type:1},
    {id:422,exercise:'Soccer',calories:7,type:1},
    {id:423,exercise:'Soccer, casual, general',calories:7,type:1},
    {id:424,exercise:'Soccer, competitive',calories:7,type:1},
    {id:425,exercise:'Softball',calories:7,type:1},
    {id:426,exercise:'Softball or baseball, fast or slow pitch',calories:7,type:1},
    {id:427,exercise:'Softball, officiating',calories:7,type:1},
    {id:428,exercise:'SoulCycle',calories:7,type:1},
    {id:429,exercise:'Spinning',calories:7,type:1},
    {id:430,exercise:'Spinning®',calories:7,type:1},
    {id:431,exercise:'Sports',calories:7,type:1},
    {id:432,exercise:'Squash',calories:7,type:1},
    {id:433,exercise:'Stair-treadmill ergometer, general',calories:7,type:1},
    {id:434,exercise:'Stand Up Paddling',calories:7,type:1},
    {id:435,exercise:'Stationary bike, general (bicycling, cycling, biking)',calories:7,type:1},
    {id:436,exercise:'Stationary bike, light effort (bicycling, cycling, biking)',calories:7,type:1},
    {id:437,exercise:'Stationary bike, moderate effort (bicycling, cycling, biking)',calories:7,type:1},
    {id:438,exercise:'Stationary bike, very light effort (bicycling, cycling, biking)',calories:7,type:1},
    {id:439,exercise:'Stationary bike, very vigorous effort (bicycling, cycling, biking)',calories:7,type:1},
    {id:440,exercise:'Stationary bike, vigorous effort (bicycling, cycling, biking)',calories:7,type:1},
    {id:441,exercise:'Step-ups, vigorous',calories:7,type:1},
    {id:442,exercise:'Strength training',calories:7,type:1},
    {id:443,exercise:'Strength training (weight lifting, weight training)',calories:7,type:1},
    {id:444,exercise:'Stretching, hatha yoga',calories:7,type:1},
    {id:445,exercise:'Stretching, sculpting',calories:7,type:1},
    {id:446,exercise:'Surfing',calories:7,type:1},
    {id:447,exercise:'Surfing, body or board',calories:7,type:1},
    {id:448,exercise:'Swimming',calories:7,type:1},
    {id:449,exercise:'Swimming laps, freestyle, fast, vigorous effort',calories:7,type:1},
    {id:450,exercise:'Swimming laps, freestyle, light/moderate effort',calories:7,type:1},
    {id:451,exercise:'Swimming, backstroke, general',calories:7,type:1},
    {id:452,exercise:'Swimming, breaststroke, general',calories:7,type:1},
    {id:453,exercise:'Swimming, butterfly, general',calories:7,type:1},
    {id:454,exercise:'Swimming, general',calories:7,type:1},
    {id:455,exercise:'Swimming, laps',calories:7,type:1},
    {id:456,exercise:'Swimming, leisurely, general',calories:7,type:1},
    {id:457,exercise:'Swimming, meet/race',calories:7,type:1},
    {id:458,exercise:'Swimming, open water',calories:7,type:1},
    {id:459,exercise:'Swimming, sidestroke, general',calories:7,type:1},
    {id:460,exercise:'Swimming, synchronized',calories:7,type:1},
    {id:461,exercise:'Swimming, treading water, fast/vigorous',calories:7,type:1},
    {id:462,exercise:'Swimming, treading water, moderate effort',calories:7,type:1},
    {id:463,exercise:'Table tennis, ping pong',calories:7,type:1},
    {id:464,exercise:'Tae Bo',calories:7,type:1},
    {id:465,exercise:'Tae Kwon Do',calories:7,type:1},
    {id:466,exercise:'Tai chi',calories:7,type:1},
    {id:467,exercise:'Teaching aerobics class',calories:7,type:1},
    {id:468,exercise:'Tennis',calories:7,type:1},
    {id:469,exercise:'Tennis, doubles',calories:7,type:1},
    {id:470,exercise:'Tennis, general',calories:7,type:1},
    {id:471,exercise:'Tennis, singles',calories:7,type:1},
    {id:472,exercise:'Title Boxing',calories:7,type:1},
    {id:473,exercise:'Toe Press',calories:7,type:1},
    {id:474,exercise:'Tonal',calories:7,type:1},
    {id:475,exercise:'Traditional cross country skiing',calories:7,type:1},
    {id:476,exercise:'Triceps Extension',calories:7,type:1},
    {id:477,exercise:'Triceps Pull-down',calories:7,type:1},
    {id:478,exercise:'Triceps Push Down',calories:7,type:1},
    {id:479,exercise:'Tricycle',calories:7,type:1},
    {id:480,exercise:'Unicycling',calories:7,type:1},
    {id:481,exercise:'Upright Row',calories:7,type:1},
    {id:482,exercise:'Volleyball',calories:7,type:1},
    {id:483,exercise:'Volleyball, beach',calories:7,type:1},
    {id:484,exercise:'Volleyball, competitive, in gymnasium',calories:7,type:1},
    {id:485,exercise:'Volleyball, noncompetitive; 6-9 member team',calories:7,type:1},
    {id:486,exercise:'Wake Surfing',calories:7,type:1},
    {id:487,exercise:'Walking',calories:7,type:1},
    {id:488,exercise:'Walking, 2.0 mph, slow pace',calories:7,type:1},
    {id:489,exercise:'Walking, 2.5 mph, downhill',calories:7,type:1},
    {id:490,exercise:'Walking, 2.5 mph, leisurely pace',calories:7,type:1},
    {id:491,exercise:'Walking, 3.0 mph, mod. pace',calories:7,type:1},
    {id:492,exercise:'Walking, 3.0 mph, mod. pace, walking dog',calories:7,type:1},
    {id:493,exercise:'Walking, 3.5 mph, brisk pace',calories:7,type:1},
    {id:494,exercise:'Walking, 3.5 mph, uphill',calories:7,type:1},
    {id:495,exercise:'Walking, 4.0 mph, very brisk pace',calories:7,type:1},
    {id:496,exercise:'Walking, 4.5 mph, very, very brisk pace',calories:7,type:1},
    {id:497,exercise:'Walking, 5.0 mph',calories:7,type:1},
    {id:498,exercise:'Walking, brisk',calories:7,type:1},
    {id:499,exercise:'Walking, carrying infant or 15-lb load',calories:7,type:1},
    {id:500,exercise:'Walking, elliptical',calories:7,type:1},
    {id:501,exercise:'Walking, general',calories:7,type:1},
    {id:502,exercise:'Walking, power',calories:7,type:1},
    {id:503,exercise:'Walking, stairs',calories:7,type:1},
    {id:504,exercise:'Walking, treadmill',calories:7,type:1},
    {id:505,exercise:'Walking, upstairs',calories:7,type:1},
    {id:506,exercise:'Walking, using crutches',calories:7,type:1},
    {id:507,exercise:'Walking, with dog',calories:7,type:1},
    {id:508,exercise:'Walking, with stroller',calories:7,type:1},
    {id:509,exercise:'Wallyball, general',calories:7,type:1},
    {id:510,exercise:'Water aerobics, water calisthenics',calories:7,type:1},
    {id:511,exercise:'Water jogging',calories:7,type:1},
    {id:512,exercise:'Water polo',calories:7,type:1},
    {id:513,exercise:'Water volleyball',calories:7,type:1},
    {id:514,exercise:'Weight workout',calories:7,type:1},
    {id:515,exercise:'Wheelchair Basketball',calories:7,type:1},
    {id:516,exercise:'Wheelchair Downhill',calories:7,type:1},
    {id:517,exercise:'Wheelchair Race',calories:7,type:1},
    {id:518,exercise:'Wheelchair Rugby',calories:7,type:1},
    {id:519,exercise:'Wheelchair Soccer',calories:7,type:1},
    {id:520,exercise:'Wheelchair Softball',calories:7,type:1},
    {id:521,exercise:'Wheelchair Tennis',calories:7,type:1},
    {id:522,exercise:'Whitewater rafting, kayaking, or canoeing',calories:7,type:1},
    {id:523,exercise:'Wii Fit Advanced Step',calories:7,type:1},
    {id:524,exercise:'Wii Fit Free Run',calories:7,type:1},
    {id:525,exercise:'Wii Fit Free Step',calories:7,type:1},
    {id:526,exercise:'Wii Fit Island Run',calories:7,type:1},
    {id:527,exercise:'Wii Fit Rhythm Boxing',calories:7,type:1},
    {id:528,exercise:'Wii Fit Super Hula Hoop',calories:7,type:1},
    {id:529,exercise:'Wii Fit exercise (advanced or high intensity)',calories:7,type:1},
    {id:530,exercise:'Wii Fit exercise (beginner or low intensity)',calories:7,type:1},
    {id:531,exercise:'Wii baseball',calories:7,type:1},
    {id:532,exercise:'Wii bowling',calories:7,type:1},
    {id:533,exercise:'Wii boxing',calories:7,type:1},
    {id:534,exercise:'Wii golf',calories:7,type:1},
    {id:535,exercise:'Wii tennis',calories:7,type:1},
    {id:536,exercise:'Workout',calories:7,type:1},
    {id:537,exercise:'Workout video',calories:7,type:1},
    {id:538,exercise:'Wrestling',calories:7,type:1},
    {id:539,exercise:'Wrist Curl',calories:7,type:1},
    {id:540,exercise:'Wrist Roller',calories:7,type:1},
    {id:541,exercise:'Yard Work',calories:7,type:1},
    {id:542,exercise:'Yoga',calories:7,type:1},
    {id:543,exercise:'Yoga Six',calories:7,type:1},
    {id:544,exercise:'Yoga to the People',calories:7,type:1},
    {id:545,exercise:'Yoga, Aerial',calories:7,type:1},
    {id:546,exercise:'Yoga, Ashtanga',calories:7,type:1},
    {id:547,exercise:'Yoga, bikram',calories:7,type:1},
    {id:548,exercise:'Yoga, hot',calories:7,type:1},
    {id:549,exercise:'Yoga, power',calories:7,type:1},
    {id:550,exercise:'Yoga, vinyasa',calories:7,type:1},
    {id:551,exercise:'YogaWorks',calories:7,type:1},
    {id:552,exercise:'Zumba',calories:7,type:1},
    {id:553,exercise:'Zumba® Fitness',calories:7,type:1},
    
    
]